#!/bin/bash
# This hook is run after this virtualenv is activated.

export PYTHONPATH=$WORKON_HOME/pygol/src/gol
export PYTHONPATH=$WORKON_HOME/pygol/src:$PYTHONPATH
export PYTHONPATH=$WORKON_HOME/pygol/src/contrib/PyGLy:$PYTHONPATH
export PYTHONPATH=$WORKON_HOME/pygol/src/contrib/Pyrr:$PYTHONPATH
